# Generated by Django 4.2.27 on 2026-01-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messageboard.messageboard'),
        ),
    ]
